### ISSUE TITLE
Microsoft Windows 7 旗舰版 6.1.7601 Service Pack 1 Build 7601安装打开报错。

### ISSUE THREAD

**Issue by shejiewu** [fandesfyf/JamTools#23]
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Users\fandes\AppData\Local\Programs\Python\Python37\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 135, in run
  File "C:\Users\fandes\AppData\Local\Programs\Python\Python37\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
  File "main.py", line 15, in <module>
  File "E:\python_dev\Jamtools\Logger.py", line 12, in <module>
  File "C:\Users\fandes\AppData\Local\Programs\Python\Python37\lib\site-packages\PyQt5\__init__.py", line 53, in <module>
  File "C:\Users\fandes\AppData\Local\Programs\Python\Python37\Lib\site-packages\cx_Freeze\hooks\pyqt5\add_library.py", line 25, in <module>
  File "C:\Users\fandes\AppData\Local\Programs\Python\Python37\Lib\site-packages\cx_Freeze\hooks\pyqt5\add_library.py", line 21, in add_path
ImportError: DLL load failed: 找不到指定的模块。

---------------------------
确定   
---------------------------
PS：
开始以为系统没有Python，去下了个python-3.7.9-amd64安装，还是一样报错！

**Comment by iamwisepig** [comment]
我也出现这个问题，看来不是python版本的问题。
